-- ==============================================
-- MIGRATION: Fix missing tables & columns (v2)
-- Updated for n8n chat_messages schema
-- ==============================================

-- 1. Add user_id column to businesses
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'user_id') THEN
  ALTER TABLE public.businesses ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
END $$;

-- 2. Add integration columns to businesses
DO $$ 
DECLARE 
    col_name TEXT;
BEGIN 
    FOR col_name IN SELECT UNNEST(ARRAY['google_calendar_id', 'brevo_api_key', 'razorpay_key_id', 'razorpay_key_secret', 'lead_notification_type']) LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
            WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = col_name) THEN
            EXECUTE format('ALTER TABLE public.businesses ADD COLUMN %I TEXT', col_name);
        END IF;
    END LOOP;
END $$;

-- 3. Create meetings table (for Calendar)
CREATE TABLE IF NOT EXISTS public.meetings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    bot_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT 'Meeting',
    guest_name TEXT,
    guest_email TEXT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER DEFAULT 30,
    status TEXT DEFAULT 'Scheduled',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'meetings' AND policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.meetings FOR SELECT USING (true);
    CREATE POLICY "Enable insert for all users" ON public.meetings FOR INSERT WITH CHECK (true);
    CREATE POLICY "Enable update for all users" ON public.meetings FOR UPDATE USING (true);
    CREATE POLICY "Enable delete for all users" ON public.meetings FOR DELETE USING (true);
  END IF;
END $$;

-- 4. Create campaigns table (for Automation)
CREATE TABLE IF NOT EXISTS public.campaigns (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    bot_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT DEFAULT 'Workflow',
    icon_color TEXT DEFAULT 'text-gray-600',
    icon_bg TEXT DEFAULT 'bg-gray-50',
    status TEXT DEFAULT 'Draft',
    triggers TEXT DEFAULT 'Webhook',
    backend TEXT DEFAULT 'n8n Workflow',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'campaigns' AND policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.campaigns FOR SELECT USING (true);
    CREATE POLICY "Enable insert for all users" ON public.campaigns FOR INSERT WITH CHECK (true);
    CREATE POLICY "Enable update for all users" ON public.campaigns FOR UPDATE USING (true);
    CREATE POLICY "Enable delete for all users" ON public.campaigns FOR DELETE USING (true);
  END IF;
END $$;

-- 5. Create chat_messages table (matching n8n Postgres Chat Memory default)
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGSERIAL PRIMARY KEY,
    "sessionId" TEXT NOT NULL, -- CamelCase column as auto-generated by n8n
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chat_messages' AND policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.chat_messages FOR SELECT USING (true);
    CREATE POLICY "Enable insert for all users" ON public.chat_messages FOR INSERT WITH CHECK (true);
  END IF;
END $$;

-- 6. Set up RLS for leads and sessions
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.leads FOR SELECT USING (true);
    CREATE POLICY "Enable insert for all users" ON public.leads FOR INSERT WITH CHECK (true);
    CREATE POLICY "Enable update for all users" ON public.leads FOR UPDATE USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chat_sessions' AND policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.chat_sessions FOR SELECT USING (true);
    CREATE POLICY "Enable insert for all users" ON public.chat_sessions FOR INSERT WITH CHECK (true);
  END IF;
END $$;

-- Done! All tables and columns should now match n8n configuration.
SELECT 'Migration completed successfully!' as status;
